<?php

/**
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

return [
    'postId_required' => 'The :attribute field is required.',
    'postId_integer' => 'The :attribute field must be an integer.',
    'postId_min' => 'The :attribute field must be at least :min.',
    'postId_attribute' => 'Post unique identification number. ',

    'parentId_integer' => 'The :attribute field must be an integer.',
    'parentId_min' => 'The :attribute field must be at least :min.',
    'parentId_attribute' => 'Parent comment unique identification number for loading replies. ',

    'limit_integer' => 'The :attribute field must be an integer.',
    'limit_min' => 'The :attribute field must be at least :min.',
    'limit_max' => 'The :attribute field must not be greater than :max.',
    'limit_attribute' => 'Maximum number of comments to return. ',

    'cursor_integer' => 'The :attribute field must be an integer.',
    'cursor_min' => 'The :attribute field must be at least :min.',
    'cursor_attribute' => 'Comment ID used for loading older comments. ',
];
