<?php

/**
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

return [

    /*
    |--------------------------------------------------------------------------
    | FeedIndexRequest Validation Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used for validation messages in FeedIndexRequest.
    | You are free to modify these language lines according to your application's requirements.
    |
    */

    'limit_integer' => 'The :attribute field must be an integer.',
    'limit_min' => 'The :attribute field must be at least :min.',
    'limit_max' => 'The :attribute field must not be greater than :max.',

    // Custom attributes for better error messages
    'limit_attribute' => "Maximum number of feed items to return. ",
    'cursor_integer' => 'The :attribute field must be an integer.',
    'cursor_min' => 'The :attribute field must be at least :min.',

    // Custom attributes for better error messages
    'cursor_attribute' => "Feed item ID used for loading older posts. ",

];
