<?php

/**
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

return [

    /*
    |--------------------------------------------------------------------------
    | LoginRequest Validation Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used for validation messages in LoginRequest.
    | You are free to modify these language lines according to your application's requirements.
    |
    */

    'email_required' => 'The :attribute field is required.',
    'email_string' => 'The :attribute field must be a string.',

    // Custom attributes for better error messages
    'email_attribute' => "Login ID in the form of an email address ",
    'password_required' => 'The :attribute field is required.',
    'password_string' => 'The :attribute field must be a string.',

    // Custom attributes for better error messages
    'password_attribute' => "The password you entered. ",

];
