<?php

/**
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

return [
    'postId_required' => 'The :attribute field is required.',
    'postId_integer' => 'The :attribute field must be an integer.',
    'postId_min' => 'The :attribute field must be at least :min.',
    'postId_attribute' => 'Post unique identification number. ',

    'parentId_integer' => 'The :attribute field must be an integer.',
    'parentId_min' => 'The :attribute field must be at least :min.',
    'parentId_attribute' => 'Parent comment unique identification number for reply creation. ',

    'body_required_without' => 'The :attribute field is required when no media file is attached.',
    'body_string' => 'The :attribute field must be a string.',
    'body_max' => 'The :attribute field must not be greater than :max characters.',
    'body_attribute' => 'Comment text content. ',

    'media_file' => 'The :attribute field must be a valid file.',
    'media_max' => 'The :attribute field must not be greater than :max kilobytes.',
    'media_attribute' => 'Comment image or voice file. ',

    'mediaType_integer' => 'The :attribute field must be an integer.',
    'mediaType_in' => 'The selected :attribute is invalid.',
    'mediaType_attribute' => 'Comment media type. ',
];
