<?php

/**
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

return [
    'postId_required' => 'The :attribute field is required.',
    'postId_integer' => 'The :attribute field must be an integer.',
    'postId_min' => 'The :attribute field must be at least :min.',
    'postId_attribute' => 'Post unique identification number. ',

    'reactionType_integer' => 'The :attribute field must be an integer.',
    'reactionType_in' => 'The selected :attribute is invalid.',
    'reactionType_attribute' => 'Reaction type. 1 means like and 2 means love. ',
];
