<?php

/**
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

return [

    /*
    |--------------------------------------------------------------------------
    | PostUserPostRequest Validation Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used for validation messages in PostUserPostRequest.
    | You are free to modify these language lines according to your application's requirements.
    |
    */

    'title_string' => 'The :attribute field must be a string.',
    'title_max' => 'The :attribute field must not be greater than :max characters.',

    // Custom attributes for better error messages
    'title_attribute' => "Optional post title. ",
    'body_required' => 'The :attribute field is required.',
    'body_string' => 'The :attribute field must be a string.',
    'body_max' => 'The :attribute field must not be greater than :max characters.',

    // Custom attributes for better error messages
    'body_attribute' => "Post text content. ",
    'visibility_integer' => 'The :attribute field must be an integer.',
    'visibility_in' => 'The selected :attribute is invalid.',

    // Custom attributes for better error messages
    'visibility_attribute' => "Post visibility. 1 means public and 2 means private. ",
    'media_file' => 'The :attribute field must be a file.',
    'media_mimes' => 'The :attribute field must be a file of type: :values.',
    'media_max' => 'The :attribute field must not be greater than :max kilobytes.',

    // Custom attributes for better error messages
    'media_attribute' => "Post image or video file. Images are converted to WebP and videos are converted to WebM. ",
    'thumbnail_image' => 'The :attribute field must be an image.',
    'thumbnail_mimes' => 'The :attribute field must be a file of type: :values.',
    'thumbnail_max' => 'The :attribute field must not be greater than :max kilobytes.',

    // Custom attributes for better error messages
    'thumbnail_attribute' => "Optional post thumbnail image. ",
    'mediaUrl_url' => 'The :attribute field must be a valid URL.',
    'mediaUrl_max' => 'The :attribute field must not be greater than :max characters.',

    // Custom attributes for better error messages
    'mediaUrl_attribute' => "Already uploaded media URL. ",
    'thumbnailUrl_url' => 'The :attribute field must be a valid URL.',
    'thumbnailUrl_max' => 'The :attribute field must not be greater than :max characters.',

    // Custom attributes for better error messages
    'thumbnailUrl_attribute' => "Already uploaded thumbnail URL. ",
    'mediaType_integer' => 'The :attribute field must be an integer.',
    'mediaType_in' => 'The selected :attribute is invalid.',

    // Custom attributes for better error messages
    'mediaType_attribute' => "Media type. 1 means image and 2 means video. ",

];
