<?php

/**
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

return [

    /*
    |--------------------------------------------------------------------------
    | RegistrationRequest Validation Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used for validation messages in RegistrationRequest.
    | You are free to modify these language lines according to your application's requirements.
    |
    */

    'firstName_required' => 'The :attribute field is required.',
    'firstName_string' => 'The :attribute field must be a string.',

    // Custom attributes for better error messages
    'firstName_attribute' => "The first name of the user. ",
    'lastName_string' => 'The :attribute field must be a string.',

    // Custom attributes for better error messages
    'lastName_attribute' => "The last name of the user. ",
    'email_required' => 'The :attribute field is required.',
    'email_string' => 'The :attribute field must be a string.',

    // Custom attributes for better error messages
    'email_attribute' => "Login ID in the form of an email address ",

    // password validation messages
    'password_required' => 'The :attribute field is required.',
    'password_string' => 'The :attribute field must be a string.',
    'password_attribute' => "New password. If not entered, an error (ApiNoInputMailAddressException) will be returned. If less than 6 characters are entered, or if the content contains only numbers, lowercase letters, or uppercase letters, an error (ApiValidatePasswordException) will be returned. (Example: abcdedg, 123456, ABCDEFG) If more than 100 characters are entered, an error (ApiValidatePasswordOverCharException) will be returned. This value will be encrypted and stored in the email address in the user table, and at the same time, a hashed version of the email address will be stored. ",

    // password confirmation validation messages
    'passwordConfirm_required' => 'The :attribute field is required.',
    'passwordConfirm_string' => 'The :attribute field must be a string.',
    // Custom attributes for better error messages
    'passwordConfirm_attribute' => "Confirm the new password. If it is different from the new password, it returns an error (ApiErrorPasswordConfirmException). ",

];
