<?php

/**
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

return [

    /*
    |--------------------------------------------------------------------------
    | SocialLoginRequest Validation Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used for validation messages in SocialLoginRequest.
    | You are free to modify these language lines according to your application's requirements.
    |
    */

    'firstName_required' => 'The :attribute field is required.',
    'firstName_string' => 'The :attribute field must be a string.',

    // Custom attributes for better error messages
    'firstName_attribute' => "The first name you entered. ",
    'lastName_string' => 'The :attribute field must be a string.',

    // Custom attributes for better error messages
    'lastName_attribute' => "The last name you entered. ",
    'email_required' => 'The :attribute field is required.',
    'email_string' => 'The :attribute field must be a string.',

    // Custom attributes for better error messages
    'email_attribute' => "Login email in the form of an email address ",
    'phone_string' => 'The :attribute field must be a string.',

    // Custom attributes for better error messages
    'phone_attribute' => "The phone number you entered. ",
    'provider_required' => 'The :attribute field is required.',
    'provider_string' => 'The :attribute field must be a string.',

    // Custom attributes for better error messages
    'provider_attribute' => "Social auth provider name ",
    'providerId_required' => 'The :attribute field is required.',
    'providerId_string' => 'The :attribute field must be a string.',

    // Custom attributes for better error messages
    'providerId_attribute' => "The provider id you entered. ",

];
